import { NextRequest, NextResponse } from 'next/server';
import { getPermissionsForSteamId, getRoleForSteamId } from '@/lib/ape-data';
import { getJobsAdminState, saveJobPostings } from '@/lib/jobs-data';
import { getSessionSteamIdFromRequest, jsonWithSession, withNoStoreHeaders } from '@/lib/session';
import { discordAuditField, notifyAdminAudit } from '@/lib/discord-webhooks';
function canManagePostings(role: string, permissions: string[]) { return role.toLowerCase() === 'developer' || permissions.includes('AdminTools'); }
function canViewStaffJobs(role: string, permissions: string[]) { return ['developer', 'admin', 'moderator'].includes(role.toLowerCase()) || permissions.includes('ViewLogs') || permissions.includes('AdminTools'); }
export async function GET(request: NextRequest) { const steamId = getSessionSteamIdFromRequest(request); if (!steamId) return jsonWithSession({ ok: false, message: 'Sign in required.' }, { status: 401 }, steamId, request); const [role, permissions] = await Promise.all([getRoleForSteamId(steamId), getPermissionsForSteamId(steamId)]); if (!canViewStaffJobs(role, permissions)) return jsonWithSession({ ok: false, message: 'Staff access required.' }, { status: 403 }, steamId, request); return jsonWithSession({ ok: true, state: await getJobsAdminState() }, undefined, steamId, request); }
export async function POST(request: NextRequest) { const steamId = getSessionSteamIdFromRequest(request); if (!steamId) return jsonWithSession({ ok: false, message: 'Sign in required.' }, { status: 401 }, steamId, request); const [role, permissions] = await Promise.all([getRoleForSteamId(steamId), getPermissionsForSteamId(steamId)]); if (!canManagePostings(role, permissions)) return jsonWithSession({ ok: false, message: 'Developer or AdminTools access required.' }, { status: 403 }, steamId, request); const body = await request.json().catch(() => ({})); const state = await saveJobPostings(body, steamId); await notifyAdminAudit({ action: 'Updated staff job postings', actor: { steamId, name: role }, severity: 'warning', url: '/staff', fields: [discordAuditField('Postings', String(state.postings.length), true), discordAuditField('Active', String(state.postings.filter((posting) => posting.status === 'active').length), true), discordAuditField('Active labels', state.postings.filter((posting) => posting.status === 'active').map((posting) => posting.title).join(', ') || 'None')] }); return jsonWithSession({ ok: true, state }, undefined, steamId, request); }
export async function OPTIONS() { return withNoStoreHeaders(new NextResponse(null, { status: 204 })); }
