import { mkdir, readFile, writeFile } from 'fs/promises';
import path from 'path';
import crypto from 'crypto';
import { getCitizenName, getPlayer } from '@/lib/ape-data';
import type { JobApplication, JobApplicationAnswer, JobApplicationNote, JobApplicationStatus, JobPosting, JobPostingStatus, JobQuestion, JobQuestionType, JobsAdminState, PublicJobsState } from '@/lib/jobs-shared';
import { allQuestionsForPosting } from '@/lib/jobs-shared';

export type { JobApplication, JobApplicationAnswer, JobApplicationNote, JobApplicationStatus, JobPosting, JobPostingStatus, JobQuestion, JobQuestionType, JobsAdminState, PublicJobsState } from '@/lib/jobs-shared';
export { DEFAULT_APPLICATION_STEPS, allQuestionsForPosting, stepsForPosting, statusLabel, postingStatusLabel } from '@/lib/jobs-shared';

type JobsStore = { postings: JobPosting[]; applications: JobApplication[] };
const nowIso = () => new Date().toISOString();
function dataDir() { return process.env.NORTHLINE_DATA_PATH?.trim() || path.join(process.cwd(), '.northline-data'); }
function storePath() { return path.join(dataDir(), 'job-portal.json'); }
async function ensureDir() { await mkdir(dataDir(), { recursive: true }); }
function clean(value: unknown, fallback: string, max: number) { const raw = String(value ?? '').replace(/\s+/g, ' ').trim(); return (raw || fallback).slice(0, max); }
function cleanLong(value: unknown, fallback: string, max: number) { const raw = String(value ?? '').replace(/\r\n/g, '\n').replace(/\n{3,}/g, '\n\n').trim(); return (raw || fallback).slice(0, max); }
export function slugify(value: unknown, fallback: string) { const raw = String(value ?? '').toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 64); return raw || fallback; }
function status(value: unknown): JobPostingStatus { return ['active', 'hidden', 'closed'].includes(String(value)) ? String(value) as JobPostingStatus : 'hidden'; }
function questionType(value: unknown): JobQuestionType { return ['short', 'long', 'yesno', 'select', 'scale'].includes(String(value)) ? String(value) as JobQuestionType : 'long'; }
function applicationStatus(value: unknown): JobApplicationStatus { return ['submitted', 'under_review', 'approved', 'declined', 'withdrawn'].includes(String(value)) ? String(value) as JobApplicationStatus : 'submitted'; }
function cleanStringArray(value: unknown, fallback: string[], maxItems = 8, maxLength = 180) { const source = Array.isArray(value) ? value : fallback; const items = source.map((item) => clean(item, '', maxLength)).filter(Boolean).slice(0, maxItems); return items.length ? items : fallback; }

export function normalizeQuestion(input: unknown, index: number): JobQuestion {
  const item = typeof input === 'object' && input !== null ? input as Record<string, unknown> : {};
  const label = clean(item.label, `Question ${index + 1}`, 160);
  const type = questionType(item.type);
  const options = Array.isArray(item.options) ? item.options.map((option) => clean(option, '', 80)).filter(Boolean).slice(0, 8) : [];
  return { id: slugify(item.id, slugify(label, `question-${index + 1}`)), label, help: clean(item.help, 'Answer honestly and clearly.', 220), type, required: item.required === undefined ? true : Boolean(item.required), ...(type === 'select' ? { options: options.length ? options : ['Option A', 'Option B'] } : {}) };
}

export function defaultPosting(): JobPosting {
  const now = nowIso();
  return {
    id: 'moderator-position', title: 'Moderator Position', department: 'Community Safety', summary: 'Help keep the servers safe, fair, and fun while supporting healthy RP scenes.',
    description: 'Moderators help players resolve conflict, answer basic questions, identify disruptive behavior, and keep roleplay moving without turning every scene into a punishment conversation.',
    commitment: '4-8 hours per week preferred. Activity during peak city hours is especially useful.', icon: 'fa-solid fa-shield-halved', accent: 'linear-gradient(135deg, #38bdf8, #2563eb)', status: 'active',
    expectations: ['Stay calm during heated player reports and scene disputes.', 'Document decisions clearly so leadership can audit actions later.', 'Teach first when possible, escalate when necessary, and avoid favoritism.'],
    qualities: ['Patient communicator', 'Comfortable reading logs and context', 'Fair under pressure', 'Good roleplay judgement'],
    questions: [
      { id: 'mod_priority', label: 'What should a moderator prioritize during a chaotic scene?', help: 'Explain what you secure first and why.', type: 'long', required: true },
      { id: 'mod_bias', label: 'How would you avoid bias when friends are involved?', help: 'Be specific about recusal, evidence, and communication.', type: 'long', required: true },
    ],
    createdAt: now, updatedAt: now, updatedBy: null,
  };
}

export function normalizePosting(input: unknown, index: number): JobPosting {
  const fallback = defaultPosting();
  const item = typeof input === 'object' && input !== null ? input as Record<string, unknown> : {};
  const title = clean(item.title, index === 0 ? fallback.title : `Job Posting ${index + 1}`, 100);
  const createdAt = clean(item.createdAt, nowIso(), 64);
  const questions = Array.isArray(item.questions) ? item.questions.map(normalizeQuestion) : [];
  return { id: slugify(item.id, slugify(title, `job-${index + 1}`)), title, department: clean(item.department, fallback.department, 80), summary: clean(item.summary, fallback.summary, 220), description: cleanLong(item.description, fallback.description, 1200), commitment: clean(item.commitment, fallback.commitment, 180), icon: clean(item.icon, fallback.icon, 80), accent: clean(item.accent, fallback.accent, 160), status: status(item.status), expectations: cleanStringArray(item.expectations, fallback.expectations), qualities: cleanStringArray(item.qualities, fallback.qualities), questions, createdAt, updatedAt: clean(item.updatedAt, createdAt, 64), updatedBy: item.updatedBy ? clean(item.updatedBy, '', 32) : null };
}

function normalizeAnswer(input: unknown, index: number): JobApplicationAnswer | null { const item = typeof input === 'object' && input !== null ? input as Record<string, unknown> : {}; const questionId = clean(item.questionId, '', 100); const label = clean(item.label, `Question ${index + 1}`, 180); const value = cleanLong(item.value, '', 4000); return questionId && label ? { questionId, label, value } : null; }
function normalizeNote(input: unknown): JobApplicationNote | null { const item = typeof input === 'object' && input !== null ? input as Record<string, unknown> : {}; const body = cleanLong(item.body, '', 1500); if (!body) return null; return { id: clean(item.id, crypto.randomUUID(), 80), authorSteamId: clean(item.authorSteamId, 'system', 32), authorRole: clean(item.authorRole, 'Staff', 80), visibility: item.visibility === 'staff' ? 'staff' : 'applicant', body, createdAt: clean(item.createdAt, nowIso(), 64) }; }
export function normalizeApplication(input: unknown): JobApplication | null { const item = typeof input === 'object' && input !== null ? input as Record<string, unknown> : {}; const steamId = clean(item.steamId, '', 32); const jobPostingId = clean(item.jobPostingId, '', 80); if (!steamId || !jobPostingId) return null; return { id: clean(item.id, crypto.randomUUID(), 80), steamId, jobPostingId, jobTitle: clean(item.jobTitle, 'Staff application', 120), status: applicationStatus(item.status), answers: Array.isArray(item.answers) ? item.answers.map(normalizeAnswer).filter(Boolean) as JobApplicationAnswer[] : [], notes: Array.isArray(item.notes) ? item.notes.map(normalizeNote).filter(Boolean) as JobApplicationNote[] : [], createdAt: clean(item.createdAt, nowIso(), 64), updatedAt: clean(item.updatedAt, nowIso(), 64), reviewedAt: item.reviewedAt ? clean(item.reviewedAt, '', 64) : null, reviewedBy: item.reviewedBy ? clean(item.reviewedBy, '', 32) : null, applicantViewedAt: item.applicantViewedAt ? clean(item.applicantViewedAt, '', 64) : null }; }
function normalizeStore(input: unknown): JobsStore { const raw = typeof input === 'object' && input !== null ? input as Record<string, unknown> : {}; const postings = Array.isArray(raw.postings) ? raw.postings.map(normalizePosting) : [defaultPosting()]; const seen = new Set<string>(); const uniquePostings = postings.map((posting, index) => { let id = posting.id; while (seen.has(id)) id = `${posting.id}-${index + 1}`; seen.add(id); return { ...posting, id }; }); return { postings: uniquePostings.length ? uniquePostings : [defaultPosting()], applications: Array.isArray(raw.applications) ? raw.applications.map(normalizeApplication).filter(Boolean) as JobApplication[] : [] }; }
async function readStore(): Promise<JobsStore> { try { const raw = await readFile(storePath(), 'utf8'); return normalizeStore(JSON.parse(raw)); } catch { return normalizeStore({ postings: [defaultPosting()], applications: [] }); } }
async function writeStore(store: JobsStore) { await ensureDir(); await writeFile(storePath(), JSON.stringify(store, null, 2), 'utf8'); }
function publicApplication(application: JobApplication, forStaff = false): JobApplication { return { ...application, notes: forStaff ? application.notes : application.notes.filter((note) => note.visibility === 'applicant') }; }

export async function getPublicJobsState(steamId?: string | null): Promise<PublicJobsState> { const store = await readStore(); return { postings: store.postings.filter((posting) => posting.status === 'active'), applications: steamId ? store.applications.filter((application) => application.steamId === steamId).map((application) => publicApplication(application)) : [] }; }
export async function getJobsAdminState(): Promise<JobsAdminState> { const store = await readStore(); const apps = store.applications.map((application) => publicApplication(application, true)); return { postings: store.postings, applications: apps.sort((a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime()), stats: { totalApplications: store.applications.length, openApplications: store.applications.filter((app) => app.status === 'submitted' || app.status === 'under_review').length, approvedApplications: store.applications.filter((app) => app.status === 'approved').length, declinedApplications: store.applications.filter((app) => app.status === 'declined').length, visiblePostings: store.postings.filter((posting) => posting.status === 'active').length, hiddenPostings: store.postings.filter((posting) => posting.status !== 'active').length } }; }
export async function saveJobPostings(input: unknown, updatedBy: string): Promise<JobsAdminState> { const store = await readStore(); const now = nowIso(); const raw = typeof input === 'object' && input !== null ? input as Record<string, unknown> : {}; const currentById = new Map(store.postings.map((posting) => [posting.id, posting])); const postings = normalizeStore({ postings: Array.isArray(raw.postings) ? raw.postings : store.postings, applications: [] }).postings.map((posting) => { const previous = currentById.get(posting.id); return { ...posting, createdAt: previous?.createdAt ?? posting.createdAt, updatedAt: now, updatedBy }; }); await writeStore({ ...store, postings }); return getJobsAdminState(); }
function answerMapFromBody(value: unknown): Record<string, string> { if (!value || typeof value !== 'object') return {}; const output: Record<string, string> = {}; for (const [key, val] of Object.entries(value as Record<string, unknown>)) output[key] = cleanLong(val, '', 4000); return output; }
export async function submitJobApplication(steamId: string, input: unknown): Promise<{ ok: boolean; message?: string; state: PublicJobsState; application?: JobApplication }> { const store = await readStore(); const body = typeof input === 'object' && input !== null ? input as Record<string, unknown> : {}; const postingId = clean(body.postingId, '', 80); const posting = store.postings.find((item) => item.id === postingId && item.status === 'active'); if (!posting) return { ok: false, message: 'That job posting is not currently accepting applications.', state: await getPublicJobsState(steamId) }; const blockingExisting = store.applications.find((application) => application.steamId === steamId && application.jobPostingId === postingId && ['submitted', 'under_review', 'approved'].includes(application.status)); if (blockingExisting) return { ok: false, message: 'You already have an active application for this posting.', state: await getPublicJobsState(steamId), application: publicApplication(blockingExisting) }; const rawAnswers = answerMapFromBody(body.answers); const questions = allQuestionsForPosting(posting); const missing = questions.filter((question) => question.required && !rawAnswers[question.id]?.trim()); if (missing.length) return { ok: false, message: `Please complete: ${missing.slice(0, 3).map((q) => q.label).join(', ')}.`, state: await getPublicJobsState(steamId) }; const player = await getPlayer(steamId); const applicantName = getCitizenName(player, steamId); const now = nowIso(); const application: JobApplication = { id: crypto.randomUUID(), steamId, jobPostingId: posting.id, jobTitle: posting.title, status: 'submitted', answers: questions.map((question) => ({ questionId: question.id, label: question.label, value: cleanLong(rawAnswers[question.id], '', 4000) })), notes: [{ id: crypto.randomUUID(), authorSteamId: 'system', authorRole: 'Portal', visibility: 'applicant', body: `Application received for ${posting.title}. Staff will review it and post updates here.`, createdAt: now }], createdAt: now, updatedAt: now, reviewedAt: null, reviewedBy: null, applicantViewedAt: now }; store.applications.unshift(application); await writeStore(store); return { ok: true, message: `Application submitted. Thanks, ${applicantName}.`, state: await getPublicJobsState(steamId), application: publicApplication(application) }; }
export async function markApplicationViewed(steamId: string, applicationId: string): Promise<PublicJobsState> { const store = await readStore(); const now = nowIso(); let changed = false; const applications = store.applications.map((application) => { if (application.id !== applicationId || application.steamId !== steamId) return application; changed = true; return { ...application, applicantViewedAt: now }; }); if (changed) await writeStore({ ...store, applications }); return getPublicJobsState(steamId); }
export async function reviewJobApplication(input: unknown, reviewerSteamId: string, reviewerRole: string): Promise<JobsAdminState> { const store = await readStore(); const body = typeof input === 'object' && input !== null ? input as Record<string, unknown> : {}; const applicationId = clean(body.applicationId, '', 80); const nextStatus = applicationStatus(body.status); const applicantNoteBody = cleanLong(body.applicantNote, '', 1500); const staffNoteBody = cleanLong(body.staffNote, '', 1500); const now = nowIso(); const applications = store.applications.map((application) => { if (application.id !== applicationId) return application; const notes = [...application.notes]; if (applicantNoteBody) notes.push({ id: crypto.randomUUID(), authorSteamId: reviewerSteamId, authorRole: reviewerRole, visibility: 'applicant', body: applicantNoteBody, createdAt: now }); if (staffNoteBody) notes.push({ id: crypto.randomUUID(), authorSteamId: reviewerSteamId, authorRole: reviewerRole, visibility: 'staff', body: staffNoteBody, createdAt: now }); const statusChanged = application.status !== nextStatus; return { ...application, status: nextStatus, notes, updatedAt: now, reviewedAt: now, reviewedBy: reviewerSteamId, applicantViewedAt: (statusChanged || applicantNoteBody) ? null : application.applicantViewedAt }; }); await writeStore({ ...store, applications }); return getJobsAdminState(); }
